// <auto-generated />
using System;
using BedBankReports.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BedBankReports.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241101104254_mig1")]
    partial class mig1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BedBankReports.API.Models.Domain.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HotelName = "GRAND PARK LARA"
                        },
                        new
                        {
                            Id = 2,
                            HotelName = "CONCORDIA CELES HOTEL"
                        },
                        new
                        {
                            Id = 3,
                            HotelName = "ROYAL WINGS HOTEL"
                        },
                        new
                        {
                            Id = 4,
                            HotelName = "HORUS PARADISE LUXURY RESORT"
                        },
                        new
                        {
                            Id = 5,
                            HotelName = "ROYAL SEGINUS"
                        },
                        new
                        {
                            Id = 6,
                            HotelName = "ALARCHA HOTELS"
                        },
                        new
                        {
                            Id = 7,
                            HotelName = "NOXINN DELUXE HOTEL"
                        },
                        new
                        {
                            Id = 8,
                            HotelName = "ADALYA ELITE LARA"
                        },
                        new
                        {
                            Id = 9,
                            HotelName = "ALAN XAFIRA DELUXE RESORT"
                        },
                        new
                        {
                            Id = 10,
                            HotelName = "SEVEN SEAS GRAVEL SELECT"
                        });
                });

            modelBuilder.Entity("BedBankReports.API.Models.Domain.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("B2B")
                        .HasColumnType("real");

                    b.Property<float>("DiffEuro")
                        .HasColumnType("real");

                    b.Property<float>("DiffPercent")
                        .HasColumnType("real");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.Property<float>("OtherToPrice")
                        .HasColumnType("real");

                    b.Property<float>("OurBestPrice")
                        .HasColumnType("real");

                    b.Property<string>("RoomType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<float>("WebBeds")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            B2B = 380f,
                            DiffEuro = 225f,
                            DiffPercent = 59.2f,
                            EndDate = new DateOnly(2025, 4, 28),
                            HotelId = 1,
                            OtherToPrice = 604.97f,
                            OurBestPrice = 380f,
                            RoomType = "Std Room",
                            StartDate = new DateOnly(2025, 4, 21),
                            WebBeds = 647.84f
                        },
                        new
                        {
                            Id = 2,
                            B2B = 980f,
                            DiffEuro = 63f,
                            DiffPercent = 6.5f,
                            EndDate = new DateOnly(2025, 6, 23),
                            HotelId = 1,
                            OtherToPrice = 1043.34f,
                            OurBestPrice = 980f,
                            RoomType = "Std Room",
                            StartDate = new DateOnly(2025, 6, 16),
                            WebBeds = 1121.26f
                        },
                        new
                        {
                            Id = 3,
                            B2B = 1080f,
                            DiffEuro = 194f,
                            DiffPercent = 18f,
                            EndDate = new DateOnly(2025, 8, 11),
                            HotelId = 1,
                            OtherToPrice = 1274.1f,
                            OurBestPrice = 1080f,
                            RoomType = "Std Room",
                            StartDate = new DateOnly(2025, 8, 4),
                            WebBeds = 1370.4f
                        },
                        new
                        {
                            Id = 4,
                            B2B = 1180f,
                            DiffEuro = -78f,
                            DiffPercent = -6.9f,
                            EndDate = new DateOnly(2025, 9, 29),
                            HotelId = 1,
                            OtherToPrice = 1043.3f,
                            OurBestPrice = 1121.3f,
                            RoomType = "Std Room",
                            StartDate = new DateOnly(2025, 9, 22),
                            WebBeds = 1121.3f
                        },
                        new
                        {
                            Id = 5,
                            B2B = 480f,
                            DiffEuro = 66f,
                            DiffPercent = 13.7f,
                            EndDate = new DateOnly(2025, 4, 28),
                            HotelId = 2,
                            OtherToPrice = 545.9f,
                            OurBestPrice = 480f,
                            RoomType = "Std Room",
                            StartDate = new DateOnly(2025, 4, 21),
                            WebBeds = 616.1f
                        },
                        new
                        {
                            Id = 6,
                            B2B = 980f,
                            DiffEuro = -106f,
                            DiffPercent = -11.8f,
                            EndDate = new DateOnly(2025, 6, 23),
                            HotelId = 2,
                            OtherToPrice = 793.1f,
                            OurBestPrice = 898.9f,
                            RoomType = "Std Room",
                            StartDate = new DateOnly(2025, 6, 16),
                            WebBeds = 898.9f
                        },
                        new
                        {
                            Id = 7,
                            B2B = 980f,
                            DiffEuro = -106f,
                            DiffPercent = -11.8f,
                            EndDate = new DateOnly(2025, 6, 23),
                            HotelId = 2,
                            OtherToPrice = 793.1f,
                            OurBestPrice = 898.9f,
                            RoomType = "Std Room",
                            StartDate = new DateOnly(2025, 6, 16),
                            WebBeds = 898.9f
                        },
                        new
                        {
                            Id = 8,
                            B2B = 1080f,
                            DiffEuro = -47f,
                            DiffPercent = -4.4f,
                            EndDate = new DateOnly(2025, 8, 11),
                            HotelId = 2,
                            OtherToPrice = 1032.5f,
                            OurBestPrice = 1080f,
                            RoomType = "Std Room",
                            StartDate = new DateOnly(2025, 8, 4),
                            WebBeds = 1170.4f
                        },
                        new
                        {
                            Id = 9,
                            B2B = 780f,
                            DiffEuro = 36f,
                            DiffPercent = 4.6f,
                            EndDate = new DateOnly(2025, 9, 29),
                            HotelId = 2,
                            OtherToPrice = 816.2f,
                            OurBestPrice = 780f,
                            RoomType = "Std Room",
                            StartDate = new DateOnly(2025, 9, 22),
                            WebBeds = 923.2f
                        },
                        new
                        {
                            Id = 10,
                            B2B = 2080f,
                            DiffEuro = 20f,
                            DiffPercent = 1.8f,
                            EndDate = new DateOnly(2025, 4, 28),
                            HotelId = 3,
                            OtherToPrice = 1151.5f,
                            OurBestPrice = 1131.3f,
                            RoomType = "Land View",
                            StartDate = new DateOnly(2025, 4, 21),
                            WebBeds = 1131.3f
                        },
                        new
                        {
                            Id = 11,
                            B2B = 2180f,
                            DiffEuro = 13f,
                            DiffPercent = 0.7f,
                            EndDate = new DateOnly(2025, 6, 23),
                            HotelId = 3,
                            OtherToPrice = 1873f,
                            OurBestPrice = 1860.1f,
                            RoomType = "Land View",
                            StartDate = new DateOnly(2025, 6, 16),
                            WebBeds = 1860.1f
                        },
                        new
                        {
                            Id = 12,
                            B2B = 2280f,
                            DiffEuro = 11f,
                            DiffPercent = 0.5f,
                            EndDate = new DateOnly(2025, 8, 11),
                            HotelId = 3,
                            OtherToPrice = 2287.1f,
                            OurBestPrice = 2276.1f,
                            RoomType = "Land View",
                            StartDate = new DateOnly(2025, 8, 4),
                            WebBeds = 2276.1f
                        },
                        new
                        {
                            Id = 13,
                            B2B = 2380f,
                            DiffEuro = 14f,
                            DiffPercent = 0.8f,
                            EndDate = new DateOnly(2025, 9, 29),
                            HotelId = 3,
                            OtherToPrice = 1811.2f,
                            OurBestPrice = 1797.4f,
                            RoomType = "Land View",
                            StartDate = new DateOnly(2025, 9, 22),
                            WebBeds = 1797.4f
                        },
                        new
                        {
                            Id = 14,
                            B2B = 400f,
                            DiffEuro = 190f,
                            DiffPercent = 47.6f,
                            EndDate = new DateOnly(2025, 4, 28),
                            HotelId = 4,
                            OtherToPrice = 590.4f,
                            OurBestPrice = 400f,
                            RoomType = "Garden Room",
                            StartDate = new DateOnly(2025, 4, 21),
                            WebBeds = 563.6f
                        },
                        new
                        {
                            Id = 15,
                            B2B = 500f,
                            DiffEuro = 316f,
                            DiffPercent = 63.1f,
                            EndDate = new DateOnly(2025, 6, 23),
                            HotelId = 4,
                            OtherToPrice = 815.7f,
                            OurBestPrice = 500f,
                            RoomType = "Garden Room",
                            StartDate = new DateOnly(2025, 6, 16),
                            WebBeds = 780.4f
                        },
                        new
                        {
                            Id = 16,
                            B2B = 600f,
                            DiffEuro = 462f,
                            DiffPercent = 77.1f,
                            EndDate = new DateOnly(2025, 8, 11),
                            HotelId = 4,
                            OtherToPrice = 1062.4f,
                            OurBestPrice = 600f,
                            RoomType = "Garden Room",
                            StartDate = new DateOnly(2025, 8, 4),
                            WebBeds = 1010.7f
                        },
                        new
                        {
                            Id = 17,
                            B2B = 700f,
                            DiffEuro = 230f,
                            DiffPercent = 32.9f,
                            EndDate = new DateOnly(2025, 9, 29),
                            HotelId = 4,
                            OtherToPrice = 930.3f,
                            OurBestPrice = 700f,
                            RoomType = "Garden Room",
                            StartDate = new DateOnly(2025, 9, 22),
                            WebBeds = 890.2f
                        },
                        new
                        {
                            Id = 18,
                            B2B = 1500f,
                            DiffEuro = 744f,
                            DiffPercent = 49.6f,
                            EndDate = new DateOnly(2025, 9, 28),
                            HotelId = 5,
                            OtherToPrice = 2440.4f,
                            OurBestPrice = 1500f,
                            RoomType = "Family Land V",
                            StartDate = new DateOnly(2025, 4, 21),
                            WebBeds = 2175.6f
                        },
                        new
                        {
                            Id = 19,
                            B2B = 1600f,
                            DiffEuro = 1643f,
                            DiffPercent = 102.7f,
                            EndDate = new DateOnly(2025, 6, 23),
                            HotelId = 5,
                            OtherToPrice = 3243.2f,
                            OurBestPrice = 1600f,
                            RoomType = "Family Land V",
                            StartDate = new DateOnly(2025, 6, 16),
                            WebBeds = 3147.7f
                        },
                        new
                        {
                            Id = 20,
                            B2B = 1700f,
                            DiffEuro = 2006f,
                            DiffPercent = 118f,
                            EndDate = new DateOnly(2025, 8, 11),
                            HotelId = 5,
                            OtherToPrice = 3705.7f,
                            OurBestPrice = 1700f,
                            RoomType = "Family Land V",
                            StartDate = new DateOnly(2025, 8, 4),
                            WebBeds = 3597.4f
                        },
                        new
                        {
                            Id = 21,
                            B2B = 1800f,
                            DiffEuro = 1172f,
                            DiffPercent = 65.1f,
                            EndDate = new DateOnly(2025, 9, 29),
                            HotelId = 5,
                            OtherToPrice = 2971.8f,
                            OurBestPrice = 1800f,
                            RoomType = "Family Land V",
                            StartDate = new DateOnly(2025, 9, 22),
                            WebBeds = 2869.3f
                        },
                        new
                        {
                            Id = 22,
                            B2B = 600f,
                            DiffEuro = 270f,
                            DiffPercent = 45f,
                            EndDate = new DateOnly(2025, 6, 23),
                            HotelId = 6,
                            OtherToPrice = 870.2f,
                            OurBestPrice = 600f,
                            RoomType = "Land View",
                            StartDate = new DateOnly(2025, 6, 16),
                            WebBeds = 832.3f
                        },
                        new
                        {
                            Id = 23,
                            B2B = 700f,
                            DiffEuro = 314f,
                            DiffPercent = 44.9f,
                            EndDate = new DateOnly(2025, 8, 11),
                            HotelId = 6,
                            OtherToPrice = 1014.4f,
                            OurBestPrice = 700f,
                            RoomType = "Land View",
                            StartDate = new DateOnly(2025, 8, 4),
                            WebBeds = 971.8f
                        },
                        new
                        {
                            Id = 24,
                            B2B = 800f,
                            DiffEuro = 106f,
                            DiffPercent = 13.3f,
                            EndDate = new DateOnly(2025, 9, 29),
                            HotelId = 6,
                            OtherToPrice = 906.2f,
                            OurBestPrice = 800f,
                            RoomType = "Land View",
                            StartDate = new DateOnly(2025, 9, 22),
                            WebBeds = 866.6f
                        },
                        new
                        {
                            Id = 25,
                            B2B = 900f,
                            DiffEuro = 32f,
                            DiffPercent = 4.1f,
                            EndDate = new DateOnly(2025, 6, 23),
                            HotelId = 7,
                            OtherToPrice = 798.6f,
                            OurBestPrice = 766.9f,
                            RoomType = "Std Room",
                            StartDate = new DateOnly(2025, 6, 16),
                            WebBeds = 766.9f
                        },
                        new
                        {
                            Id = 26,
                            B2B = 1000f,
                            DiffEuro = 40f,
                            DiffPercent = 4f,
                            EndDate = new DateOnly(2025, 8, 11),
                            HotelId = 7,
                            OtherToPrice = 1037.6f,
                            OurBestPrice = 998f,
                            RoomType = "Std Room",
                            StartDate = new DateOnly(2025, 8, 4),
                            WebBeds = 998f
                        },
                        new
                        {
                            Id = 27,
                            B2B = 1100f,
                            DiffEuro = 26f,
                            DiffPercent = 5f,
                            EndDate = new DateOnly(2025, 9, 29),
                            HotelId = 7,
                            OtherToPrice = 537f,
                            OurBestPrice = 511.2f,
                            RoomType = "Std Room",
                            StartDate = new DateOnly(2025, 9, 22),
                            WebBeds = 511.2f
                        },
                        new
                        {
                            Id = 28,
                            B2B = 900f,
                            DiffEuro = 113f,
                            DiffPercent = 17.4f,
                            EndDate = new DateOnly(2025, 4, 28),
                            HotelId = 8,
                            OtherToPrice = 900f,
                            OurBestPrice = 766.9f,
                            RoomType = "no-room-type",
                            StartDate = new DateOnly(2025, 4, 21),
                            WebBeds = 766.9f
                        },
                        new
                        {
                            Id = 29,
                            B2B = 1000f,
                            DiffEuro = 2f,
                            DiffPercent = 0.2f,
                            EndDate = new DateOnly(2025, 6, 23),
                            HotelId = 8,
                            OtherToPrice = 1000f,
                            OurBestPrice = 998f,
                            RoomType = "no-room-type",
                            StartDate = new DateOnly(2025, 6, 16),
                            WebBeds = 998f
                        },
                        new
                        {
                            Id = 30,
                            B2B = 1100f,
                            DiffEuro = 589f,
                            DiffPercent = 115.2f,
                            EndDate = new DateOnly(2025, 8, 11),
                            HotelId = 8,
                            OtherToPrice = 1100f,
                            OurBestPrice = 511.2f,
                            RoomType = "no-room-type",
                            StartDate = new DateOnly(2025, 8, 4),
                            WebBeds = 511.2f
                        },
                        new
                        {
                            Id = 31,
                            B2B = 1100f,
                            DiffEuro = 589f,
                            DiffPercent = 115.2f,
                            EndDate = new DateOnly(2025, 9, 29),
                            HotelId = 8,
                            OtherToPrice = 1100f,
                            OurBestPrice = 511.2f,
                            RoomType = "no-room-type",
                            StartDate = new DateOnly(2025, 9, 22),
                            WebBeds = 511.2f
                        },
                        new
                        {
                            Id = 32,
                            B2B = 900f,
                            DiffEuro = 113f,
                            DiffPercent = 17.4f,
                            EndDate = new DateOnly(2025, 4, 28),
                            HotelId = 9,
                            OtherToPrice = 900f,
                            OurBestPrice = 766.9f,
                            RoomType = "no-room-type",
                            StartDate = new DateOnly(2025, 4, 21),
                            WebBeds = 766.9f
                        },
                        new
                        {
                            Id = 33,
                            B2B = 100f,
                            DiffEuro = 2f,
                            DiffPercent = 0.2f,
                            EndDate = new DateOnly(2025, 6, 23),
                            HotelId = 9,
                            OtherToPrice = 1000f,
                            OurBestPrice = 998f,
                            RoomType = "no-room-type",
                            StartDate = new DateOnly(2025, 6, 16),
                            WebBeds = 998f
                        },
                        new
                        {
                            Id = 34,
                            B2B = 1100f,
                            DiffEuro = 589f,
                            DiffPercent = 115.2f,
                            EndDate = new DateOnly(2025, 8, 11),
                            HotelId = 9,
                            OtherToPrice = 1100f,
                            OurBestPrice = 511.2f,
                            RoomType = "no-room-type",
                            StartDate = new DateOnly(2025, 8, 4),
                            WebBeds = 511.2f
                        },
                        new
                        {
                            Id = 35,
                            B2B = 1100f,
                            DiffEuro = 589f,
                            DiffPercent = 115.2f,
                            EndDate = new DateOnly(2025, 9, 9),
                            HotelId = 9,
                            OtherToPrice = 1100f,
                            OurBestPrice = 511.2f,
                            RoomType = "no-room-type",
                            StartDate = new DateOnly(2025, 9, 22),
                            WebBeds = 511.2f
                        },
                        new
                        {
                            Id = 36,
                            B2B = 900f,
                            DiffEuro = 133f,
                            DiffPercent = 17.4f,
                            EndDate = new DateOnly(2025, 4, 28),
                            HotelId = 10,
                            OtherToPrice = 900f,
                            OurBestPrice = 766.9f,
                            RoomType = "no-room-type",
                            StartDate = new DateOnly(2025, 4, 21),
                            WebBeds = 766.9f
                        },
                        new
                        {
                            Id = 37,
                            B2B = 1000f,
                            DiffEuro = 2f,
                            DiffPercent = 0.2f,
                            EndDate = new DateOnly(2025, 6, 23),
                            HotelId = 10,
                            OtherToPrice = 1000f,
                            OurBestPrice = 998f,
                            RoomType = "no-room-type",
                            StartDate = new DateOnly(2025, 6, 16),
                            WebBeds = 998f
                        },
                        new
                        {
                            Id = 38,
                            B2B = 1100f,
                            DiffEuro = 589f,
                            DiffPercent = 115.2f,
                            EndDate = new DateOnly(2025, 8, 11),
                            HotelId = 10,
                            OtherToPrice = 1100f,
                            OurBestPrice = 511.2f,
                            RoomType = "no-room-type",
                            StartDate = new DateOnly(2025, 8, 4),
                            WebBeds = 511.2f
                        },
                        new
                        {
                            Id = 39,
                            B2B = 1100f,
                            DiffEuro = 589f,
                            DiffPercent = 115.2f,
                            EndDate = new DateOnly(2025, 8, 11),
                            HotelId = 10,
                            OtherToPrice = 1100f,
                            OurBestPrice = 511.2f,
                            RoomType = "no-room-type",
                            StartDate = new DateOnly(2025, 8, 4),
                            WebBeds = 511.2f
                        });
                });

            modelBuilder.Entity("BedBankReports.API.Models.Domain.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<float?>("FinalCost")
                        .HasColumnType("real");

                    b.Property<float?>("FinalProfit")
                        .HasColumnType("real");

                    b.Property<float?>("FinalProfitPercent")
                        .HasColumnType("real");

                    b.Property<float?>("FinalSales")
                        .HasColumnType("real");

                    b.Property<int?>("Paxes")
                        .HasColumnType("int");

                    b.Property<int?>("ReservationCount")
                        .HasColumnType("int");

                    b.Property<int?>("RoomNights")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateOnly(2024, 10, 1),
                            FinalCost = 1500f,
                            FinalProfit = 1000f,
                            FinalProfitPercent = 66.67f,
                            FinalSales = 2500f,
                            Paxes = 50,
                            ReservationCount = 5,
                            RoomNights = 50
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateOnly(2024, 10, 2),
                            FinalCost = 2000f,
                            FinalProfit = 500f,
                            FinalProfitPercent = 25f,
                            FinalSales = 2500f,
                            Paxes = 60,
                            ReservationCount = 6,
                            RoomNights = 60
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateOnly(2024, 10, 3),
                            FinalCost = 1000f,
                            FinalProfit = 150f,
                            FinalProfitPercent = 15f,
                            FinalSales = 1500f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateOnly(2024, 10, 4),
                            FinalCost = 4500f,
                            FinalProfit = 400f,
                            FinalProfitPercent = 8.99f,
                            FinalSales = 4900f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateOnly(2024, 10, 5),
                            FinalCost = 985f,
                            FinalProfit = 65f,
                            FinalProfitPercent = 6.6f,
                            FinalSales = 1050f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateOnly(2024, 10, 6),
                            FinalCost = 900f,
                            FinalProfit = 600f,
                            FinalProfitPercent = 66.67f,
                            FinalSales = 1500f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateOnly(2024, 10, 7),
                            FinalCost = 900f,
                            FinalProfit = 250f,
                            FinalProfitPercent = 38.89f,
                            FinalSales = 1250f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateOnly(2024, 10, 8),
                            FinalCost = 900f,
                            FinalProfit = -150f,
                            FinalProfitPercent = -16.67f,
                            FinalSales = 750f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateOnly(2024, 10, 9),
                            FinalCost = 6800f,
                            FinalProfit = 1100f,
                            FinalProfitPercent = 16.18f,
                            FinalSales = 7900f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateOnly(2024, 10, 10),
                            FinalCost = 4900f,
                            FinalProfit = 1080f,
                            FinalProfitPercent = 22.04f,
                            FinalSales = 5980f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateOnly(2024, 10, 11),
                            FinalCost = 9600f,
                            FinalProfit = 1300f,
                            FinalProfitPercent = 13.54f,
                            FinalSales = 10900f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateOnly(2024, 10, 12),
                            FinalCost = 1500f,
                            FinalProfit = 1400f,
                            FinalProfitPercent = 93.33f,
                            FinalSales = 2900f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateOnly(2024, 10, 13),
                            FinalCost = 1900f,
                            FinalProfit = 840f,
                            FinalProfitPercent = 44.21f,
                            FinalSales = 2740f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateOnly(2024, 10, 14),
                            FinalCost = 3250f,
                            FinalProfit = 230f,
                            FinalProfitPercent = 7.08f,
                            FinalSales = 3480f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateOnly(2024, 10, 15),
                            FinalCost = 4900f,
                            FinalProfit = 450f,
                            FinalProfitPercent = 9.18f,
                            FinalSales = 5350f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateOnly(2024, 10, 16),
                            FinalCost = 1500f,
                            FinalProfit = 460f,
                            FinalProfitPercent = 30.67f,
                            FinalSales = 1960f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateOnly(2024, 10, 17),
                            FinalCost = 1400f,
                            FinalProfit = 90f,
                            FinalProfitPercent = 6.43f,
                            FinalSales = 1490f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateOnly(2024, 10, 18),
                            FinalCost = 3900f,
                            FinalProfit = 250f,
                            FinalProfitPercent = 6.41f,
                            FinalSales = 4150f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateOnly(2024, 10, 19),
                            FinalCost = 4900f,
                            FinalProfit = 140f,
                            FinalProfitPercent = 2.86f,
                            FinalSales = 5040f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateOnly(2024, 10, 20),
                            FinalCost = 1600f,
                            FinalProfit = -100f,
                            FinalProfitPercent = -6.25f,
                            FinalSales = 1500f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateOnly(2024, 10, 21),
                            FinalCost = 1460f,
                            FinalProfit = -70f,
                            FinalProfitPercent = -4.79f,
                            FinalSales = 1390f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateOnly(2024, 10, 22),
                            FinalCost = 1500f,
                            FinalProfit = 290f,
                            FinalProfitPercent = 19.33f,
                            FinalSales = 1790f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateOnly(2024, 10, 23),
                            FinalCost = 3500f,
                            FinalProfit = 150f,
                            FinalProfitPercent = 4.29f,
                            FinalSales = 3650f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateOnly(2024, 10, 24),
                            FinalCost = 1100f,
                            FinalProfit = 149f,
                            FinalProfitPercent = 13.55f,
                            FinalSales = 1249f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateOnly(2024, 10, 25),
                            FinalCost = 2600f,
                            FinalProfit = 190f,
                            FinalProfitPercent = 7.31f,
                            FinalSales = 2790f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateOnly(2024, 10, 26),
                            FinalCost = 2250f,
                            FinalProfit = 485f,
                            FinalProfitPercent = 21.56f,
                            FinalSales = 2735f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateOnly(2024, 10, 27),
                            FinalCost = 5600f,
                            FinalProfit = 380f,
                            FinalProfitPercent = 6.79f,
                            FinalSales = 5980f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateOnly(2024, 10, 28),
                            FinalCost = 5100f,
                            FinalProfit = 225f,
                            FinalProfitPercent = 4.41f,
                            FinalSales = 5325f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateOnly(2024, 10, 29),
                            FinalCost = 3100f,
                            FinalProfit = 850f,
                            FinalProfitPercent = 27.42f,
                            FinalSales = 3950f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateOnly(2024, 10, 30),
                            FinalCost = 3500f,
                            FinalProfit = 250f,
                            FinalProfitPercent = 7.17f,
                            FinalSales = 3750f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateOnly(2024, 10, 31),
                            FinalCost = 4550f,
                            FinalProfit = 420f,
                            FinalProfitPercent = 9.23f,
                            FinalSales = 4970f,
                            Paxes = -1,
                            ReservationCount = -1,
                            RoomNights = -1
                        });
                });

            modelBuilder.Entity("BedBankReports.API.Models.Domain.Rate", b =>
                {
                    b.HasOne("BedBankReports.API.Models.Domain.Hotel", "Hotel")
                        .WithMany("Rates")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("BedBankReports.API.Models.Domain.Hotel", b =>
                {
                    b.Navigation("Rates");
                });
#pragma warning restore 612, 618
        }
    }
}
